import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import data from '../data/education.json'
import { useState } from 'react'
import Card from '../components/Card'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  console.log(data);
  const [information, setInformation] = useState([...data])

  return (
    <>
      <Head>
        <title>Lina Columbia Institute of Technology</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Lina Columbia Institute of Technology</h1>
        <Link className={styles.about} href="about">About Us</Link>
        <h1 className={styles.programs}>Our Programs</h1>

        <div className={styles.cards}>
        {
          information && information.map((info, index) => {
            if(info.department.toLowerCase() === "business"){ 
              return(
                <Card 
                  className={styles.business__card}
                  key={index} 
                  degree={info.degree} 
                  color="#F7B2B7"
                  font="30px" 
                />
              )
            }

            if(info.department.toLowerCase() === "computing"){ 
              return(
                <Card 
                  className={styles.computing__card}
                  key={index} 
                  degree={info.degree} 
                  color="#DE639A"
                  font="30px" 
                />
              )
            }
          })
        }
        </div>
      </main>
    </>
  )
}
